### ISSUE TITLE
Syntax error: newline unexpected in N4_th

### ISSUE THREAD

**Issue by gvalvano** [krishnabits001/task_driven_data_augmentation#1]
Hello :) many thanks for sharing this code, and the great paper.

I'm trying to run the bias correction pipeline you shared. However, running the command:

`./N4_th input_filename.nii.gz output_filename.nii.gz 0.001`

incurs in the following error:

> ./N4_th: 7: ./N4_th: Syntax error: newline unexpected

As you explained [here](https://github.com/krishnabits001/task_driven_data_augmentation/blob/master/bias_correction_details.txt), I downloaded the "N4_th" file, and I changed it to be executable using: `chmod +x N4_th`. But then, running the above command gives me the newline unexpected error.

Did I forget anything/misunderstand the instructions?

Thanks for the help,
Gabriele

**Comment by krishnabits001** [comment]
Dear Gabriele,

Glad that you liked the article and found the code useful.

The N4_th file was compiled using cmake on the N4 bias correction files provided by ITK software.
I guess the executable file generated post compilation is specific to the linux version it has been compiled on and is not working on other OS / linux versions.
You could possibly download these files (which I am adding in 'N4 compile_files' folder in git repo) and compile it using cmake in your PC so that it generates executable that works on your PC. 
Prior to compilation, one needs to download cmake & edit the paths in CMakeCache.txt appropriately.

An **easier** option would be to do N4 bias correction using python and itk packages (same ones as compiled here).
https://simpleitk.readthedocs.io/en/master/link_N4BiasFieldCorrection_docs.html

Regards,
Krishna Chaitanya

**Comment by gvalvano** [comment]
Dear Krishna, 

thank you for your kind answer. Following the ITK guidelines is the simplest option, indeed. I leave my steps below, for who may encounter the same issues (could you please confirm these are the exact same steps you followed, too?):

```
import SimpleITK as sitk

# parameters for ACDC
threshold_value = 0.001
n_fitting_levels = 4
n_iters = 50

inputImage = sitk.ReadImage(in_file_name)
inputImage = sitk.Cast(inputImage, sitk.sitkFloat32)

corrector = sitk.N4BiasFieldCorrectionImageFilter()
corrector.SetConvergenceThreshold(threshold_value)
corrector.SetMaximumNumberOfIterations([int(n_iters)] * n_fitting_levels)

output = corrector.Execute(inputImage)
sitk.WriteImage(output, out_file_name)
```

Thanks a lot,
Gabriele

**Comment by krishnabits001** [comment]
Dear Gabriele,

Thank you for posting the steps in python here.
Yes, the steps you have posted are correct.

Just one needs to define the in_file_name and out_file_name variables or the user can pass them as arguments in the command line.

Regards,
Krishna Chaitanya

**Comment by krishnabits001** [comment]
Thanks Gabriele for posting the steps on the git repo as well. They are quite useful! 😊

I hope you have a great week ahead! 😃



Regards,
Krishna Chaitanya
PhD Student,
Computer Vision Laboratory | ETH Zürich
Sternwartstrasse 7 | ETF E 112 | 8092 Zürich, Switzerland

________________________________
